# Generated by Django 5.2.2 on 2025-07-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_esi_auth", "0002_create_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eveentity",
            name="eve_entity_type",
            field=models.CharField(
                choices=[
                    ("character", "Character"),
                    ("corporation", "Corporation"),
                    ("alliance", "Alliance"),
                    ("station", "Station"),
                    ("structure", "Structure"),
                    ("unknown", "Unknown"),
                ]
            ),
        ),
    ]
