# Generated by Django 5.2.2 on 2025-07-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_esi_auth", "0003_alter_eveentity_eve_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eveentity",
            name="eve_entity_name",
            field=models.CharField(default="Unknown"),
        ),
    ]
