# Generated by Django 5.2.2 on 2025-07-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_esi_auth", "0004_alter_eveentity_eve_entity_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eveentity",
            name="eve_entity_id",
            field=models.BigIntegerField(),
        ),
    ]
